#!/bin/bash
# =============================================================================
# docker.sh — Dev/test launcher for Achievement Engine
# Ubuntu VM with Docker / docker compose
#
# Usage:
#   ./docker.sh          — build both images and start everything
#   ./docker.sh up       — start without rebuilding
#   ./docker.sh build    — build only (no start)
#   ./docker.sh down     — stop and remove containers
#   ./docker.sh restart  — down + up (no rebuild)
#   ./docker.sh logs     — tail both container logs
#   ./docker.sh status   — show container health
# =============================================================================

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR/../../"

CMD="${1:-}"

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${CYAN}[info]${NC} $*"; }
success() { echo -e "${GREEN}[ok]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC} $*"; }
err()     { echo -e "${RED}[err]${NC}  $*"; }
header()  { echo -e "\n${BOLD}${CYAN}═══ $* ═══${NC}"; }

# ── Dependency check ───────────────────────────────────────────────────────────
check_deps() {
    if ! command -v docker &>/dev/null; then
        err "Docker is not installed. Run: curl -fsSL https://get.docker.com | sh"
        exit 1
    fi
    # Support both 'docker compose' (v2 plugin) and 'docker-compose' (v1 standalone)
    if docker compose version &>/dev/null 2>&1; then
        DC="docker compose"
    elif command -v docker-compose &>/dev/null; then
        DC="docker-compose"
    else
        err "docker compose not found. Install Docker Desktop or 'sudo apt install docker-compose-plugin'"
        exit 1
    fi
    success "Docker: $(docker --version)"
    success "Compose: $($DC version)"
}

# ── .env setup ─────────────────────────────────────────────────────────────────
ensure_env() {
    if [ -f ".env" ]; then
        info ".env found — using existing config."
        return
    fi

    warn ".env not found. Creating a minimal test .env..."
    echo ""
    echo -e "${YELLOW}You'll need these values to connect to Audiobookshelf.${NC}"
    echo -e "Leave blank to skip (the engine starts but can't pull ABS data)."
    echo ""

    read -rp "  ABS_URL (e.g. http://192.168.1.x:13378) : " ABS_URL_VAL
    read -rp "  ABS_TOKEN (your ABS API token)           : " ABS_TOKEN_VAL
    read -rp "  DISCORD_WEBHOOK_URL (optional)           : " DISCORD_VAL

    cat > .env << EOF
# Achievement Engine — Test Environment
# Generated by docker.sh on $(date)

# --- ABS Connection ---
ABSSTATS_BASE_URL=http://abs-stats:3000
ABS_URL=${ABS_URL_VAL}
ABS_TOKEN=${ABS_TOKEN_VAL}

# --- Discord (optional) ---
DISCORD_WEBHOOK_URL=${DISCORD_VAL}
DISCORD_PROXY_URL=http://abs-stats:3000/api/discord-notify

# --- Engine behaviour ---
POLL_SECONDS=60
ACHIEVEMENTS_SCOPE=all_time
PROGRESSION_SCOPE=all_time
WRAPPED_ENABLED=false
EOF
    success ".env created."
}

# ── Data directories ───────────────────────────────────────────────────────────
ensure_data_dirs() {
    info "Ensuring data directories exist..."
    mkdir -p data/json data/csv data/covers icons avatars covers
    # Fix line endings on setup.sh (important when cloned on Windows)
    if command -v dos2unix &>/dev/null; then
        dos2unix setup.sh &>/dev/null || true
    else
        sed -i 's/\r$//' setup.sh 2>/dev/null || true
    fi
    chmod +x setup.sh
    success "Data directories ready."
}

# ── Build ──────────────────────────────────────────────────────────────────────
do_build() {
    header "Building images"
    info "Building abs-stats..."
    $DC build abs-stats
    success "abs-stats built."
    info "Building achievement-engine..."
    $DC build achievement-engine
    success "achievement-engine built."
}

# ── Up ─────────────────────────────────────────────────────────────────────────
do_up() {
    header "Starting containers"
    $DC up -d
    echo ""
    info "Waiting for containers to initialise..."
    sleep 4
    do_status
}

# ── Down ───────────────────────────────────────────────────────────────────────
do_down() {
    header "Stopping containers"
    $DC down
    success "All containers stopped."
}

# ── Logs ───────────────────────────────────────────────────────────────────────
do_logs() {
    header "Tailing logs (Ctrl+C to stop)"
    $DC logs -f --tail=50
}

# ── Status ─────────────────────────────────────────────────────────────────────
do_status() {
    header "Container status"
    $DC ps

    HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

    echo ""
    echo -e "${BOLD}Access URLs:${NC}"
    echo -e "  Achievement Engine  →  ${GREEN}http://${HOST_IP}:8000${NC}"
    echo -e "  Release Radar       →  ${GREEN}http://${HOST_IP}:8000/radar${NC}"
    echo -e "  abs-stats           →  ${GREEN}http://${HOST_IP}:3000${NC}"
    echo ""
    echo -e "${BOLD}Useful commands:${NC}"
    echo -e "  ./docker.sh logs     — tail live logs"
    echo -e "  ./docker.sh down     — stop everything"
    echo -e "  ./docker.sh restart  — restart without rebuild"
}

# ── Router ─────────────────────────────────────────────────────────────────────
check_deps

case "$CMD" in
    build)
        ensure_data_dirs
        ensure_env
        do_build
        ;;
    up)
        ensure_data_dirs
        ensure_env
        do_up
        ;;
    down)
        do_down
        ;;
    restart)
        do_down
        ensure_data_dirs
        do_up
        ;;
    logs)
        do_logs
        ;;
    status)
        do_status
        ;;
    "")
        # Default: build everything then start
        ensure_data_dirs
        ensure_env
        do_build
        do_up
        ;;
    *)
        echo "Unknown command: $CMD"
        echo "Usage: ./docker.sh [up|down|build|restart|logs|status]"
        exit 1
        ;;
esac
